### ISSUE TITLE
Allow the latest version of the dependencies.

### ISSUE THREAD

**Issue by jh-wu** [liampauling/betfair#230]
The dependencies of this project are fixed at the versions defined in the requirements.txt. Just wondering if it's possible to allow the latest versions?

requests==2.21.0
ciso8601==2.0.1
ujson==1.35

**Comment by liampauling** [comment]
Hi, as per best practise versions are included, this was added due to the volatile nature of the requests release practise which has historically caused issues:

https://github.com/psf/requests/issues/4006

You can either download and update the requirements yourself or just update the library after installing. I can't risk removing the versions due to the impact it could have on builds that rely on betfairlightweight.

**Comment by jh-wu** [comment]
No, I am not suggesting to remove the versions. Quite the contrary, I am suggesting to test the project on the latest depended packages, as I think sticking the dependencies on certain fixed versions isn't the best practice. All popular projects (to my best knowledge) would allow a certain flexibility in terms of dependencies, for example in Pandas: https://github.com/pandas-dev/pandas/blob/master/requirements-dev.txt. This I believe will help users avoiding being in conflicting situation with other packages. 

I think what we have to do here is quite straightforward, just to run the test cases on the requests 2.22.0 and ciso8601 2.1.1. If they work well, simple changing the requirements.txt to be:
requests>=2.21.0,<=2.22.0
ciso8601>=2.0.1,<=2.1.1
ujson>=1.35

**Comment by liampauling** [comment]
Because of the libraries which are used in this library have reached a stable release I don't see the need in having the latest, however I do normally update when I do a release. 

It's entirely possible that a minor release could break something (as we have seen before with requests). It is then possible that this is built into a docker image which I (or anyone else) uses in production, I have too much money on the line to take this sort of risk.
